In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3], [1.0, 3.0, 5.0]])
print(b)

[[1. 2. 3.]
 [1. 3. 5.]]


In [4]:
#Get Dimension
a.ndim

1

In [5]:
#Get Shape
b.shape

(2, 3)

In [7]:
#Get Type
b.dtype

dtype('float64')

In [14]:
#Get item Size (bytes)
b.itemsize

8

In [13]:
#Total size
b.nbytes

48

In [17]:
#Get a specific element
b[0][2]

3.0

In [19]:
#Row
b[0,:]

array([1., 2., 3.])

In [20]:
c = np.array([1,2,3,4,5,6,7,8,9])

In [25]:
#[start index:end index:stepsize] - end index is exclusive
c[1:5:2]

array([2, 4])

In [26]:
c[5] = 101
print(c)

[  1   2   3   4   5 101   7   8   9]


# Array Creation methods

In [31]:
#ALL 0s/1s matrix
np.zeros((2,3))
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.full((2,3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [34]:
# Array with same shape as b, but all 3s
np.full_like(b,3)

array([[3., 3., 3.],
       [3., 3., 3.]])

In [35]:
np.full_like(a,2) # Maintains datatype

array([2, 2, 2], dtype=int16)

In [37]:
# Random decimal numbers - pass dimensions as individual arguments instead of a tuple
np.random.rand(4,2,3)

array([[[0.11421421, 0.32220204, 0.63013021],
        [0.02530703, 0.04468539, 0.67068257]],

       [[0.35222964, 0.31006486, 0.73064892],
        [0.1720492 , 0.79341644, 0.3119225 ]],

       [[0.72693575, 0.23659994, 0.41035096],
        [0.82311284, 0.41212724, 0.78507461]],

       [[0.92897128, 0.00558225, 0.6873026 ],
        [0.09928136, 0.10327109, 0.3675062 ]]])

In [38]:
np.random.random_sample(a.shape)

array([0.61720588, 0.28259632, 0.18341738])

In [41]:
# Random integers
np.random.randint(-4, 7, size=(3,3))

array([[ 0, -3,  0],
       [-4,  5,  1],
       [-4, -3,  1]])

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [51]:
arrr = np.array([[1,2,3]])
r2 = np.repeat(arrr,3,axis=0)
r3 = np.repeat(arrr,3,axis=1)
r4 = np.repeat(arrr,3) #default is flattened array output
print(r2)
print(r3)
print(r4)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]
[1 1 1 2 2 2 3 3 3]


In [58]:
# Challenge
ac = np.ones((5,5))
ac[1:4,1:4] = 0
ac[2,2] = 9
print(ac)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
# Challenge alt

ad = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
ad[1:4,1:4]=z
print(ad)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copies

In [61]:
a = [1,3,5]
b=a.copy()
print(b)

[1, 3, 5]


## Linear Algebra

In [63]:
# Matrix multiplication
a = np.full((2,3),1)
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [64]:
# Matrix determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [66]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.min(stats)
np.max(stats)

6

In [68]:
np.min(stats, axis=1)

array([1, 4])

In [71]:
np.sum(stats, axis=1)

array([ 6, 15])